name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: User Metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.user.svg
          token: ${{ secrets.FESTIVITIES_METRICS }}
          user: festivities
          retries: 3
          retries_delay: 300
          plugins_errors_fatal: yes

      - name: Achievements
        uses: festivities/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.FESTIVITIES_METRICS }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: maintainer
          delay: 120
          retries: 3
          retries_delay: 300
          user: festivities
          plugins_errors_fatal: yes

      - name: Recent activity
        uses: festivities/metrics@master
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.FESTIVITIES_METRICS }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          delay: 120
          retries: 3
          retries_delay: 300
          user: festivities
          plugins_errors_fatal: yes

      - name: Most used
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.FESTIVITIES_METRICS }}
          base: ""
          commits_authoring: festivities, festivities@users.noreply.github.com, admin@festivity.moe
          plugin_languages: yes
          plugin_languages_skipped: festivities
          plugin_languages_limit: 24
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
